spring:
 application:
  name: My-Config-Server-Dev-Env-RATING_SERVICE
# Eureka server client configration
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
