# spring:
#  application:
main:
  valuehai:
    info: 5000
#   name: My-Central-Config-Server
# Eureka server client configration
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

